sudo: false
language: php
php:
- 7.3
- 7.4
cache:
  directories:
    - $HOME/.composer/cache
before_install:
- composer self-update
- composer validate --no-check-all --ansi
install:
- travis_retry composer install --no-interaction --prefer-source
script:
- cd ${TRAVIS_BUILD_DIR}
- composer test
after_success:
- cd ${TRAVIS_BUILD_DIR}
- composer coveralls
